// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eosulcourcwvrlgkaiwv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVvc3VsY291cmN3dnJsZ2thaXd2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzY5OTIzOTMsImV4cCI6MjA1MjU2ODM5M30.cIqyoc-qfsTJn6zCmF-UlUXKhYcpYijLTqjtf-glpqc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);